[package]
name = "txn_verification"
type = "bin"
authors = [""]
compiler_version = ">=0.26.0"

[dependencies]
base58 = { tag = "v0.1.0", git = "https://github.com/alpinevm/base58-noir" }
bech32 = { tag = "v0.1.0", git = "https://github.com/alpinevm/bech32-noir" }
rift_lib = { path = "../lib" }
