[package]
name = "rift-core"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sha2 = {  workspace = true }
crypto-bigint = {  workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
