[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
rift-lib = { path = "../lib" }
bitcoin = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
crypto-bigint = { workspace = true }


