BB = "~/.nargo/backends/acvm-backend-barretenberg/backend_binary"
MAX_ENCODED_CHUNKS = 226
MAX_LIQUIDITY_PROVIDERS = 175
MAX_INNER_BLOCKS = 24
CONFIRMATION_BLOCK_DELTA = 5
MAX_BLOCK_HASHES_PER_BASE_PROOF = 90
MAX_BLOCK_HASHES_PER_ENTRYPOINT_PROOF = 750
MAX_BLOCK_PROOFS = MAX_BLOCK_HASHES_PER_ENTRYPOINT_PROOF // MAX_BLOCK_HASHES_PER_BASE_PROOF
